### ISSUE TITLE
IE / Edge

### ISSUE THREAD

**Issue by testower** [researchgate/react-intersection-observer#16]
## Expected behavior
According to docs, this component should work with IE11 with a polyfill, and with Edge 15 without a polyfill.

## Current behavior
I am unable to even get the storybook example to work in Edge 15. The onChange action logger reports undefined for "isIntersecting".

## Steps to reproduce
1. Open the storybook example in Edge 15
2. Observe that the example doesn't work

* **Version**: 0.4.2
* **Platform**:  Browserstack + Edge 15

**Comment by Rendez** [comment]
@testower thanks for your detailed report. Unfortunately, I will only have access to an Edge browser tomorrow morning.

In the meantime, can you please confirm which version of the polyfill are you using? Some support for Edge 15 was added [not long ago](https://github.com/w3c/IntersectionObserver/pull/224).

Also note that while this issue is fixed on Edge, hasn't been shipped just yet: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/12156111/

**Comment by testower** [comment]
Cheers, the version I referred to above was the polyfill version, sorry about that.

Would that polyfill not fix the issue on Edge meanwhile?

Also, I seem to have a hard time in IE11, on my end, but unable to give steps at this point. It seems to me that the onChange doesn't fire at all.

**Comment by Rendez** [comment]
@testower It struck me a moment ago that I did not include the polyfill in the storybook's JS bundle. I will fix this tomorrow. Now, this only affects the storybook example page and including the polyfill in your codebase as usual should work as expected, and trigger onChange even in IE11.

To be clear, this is a bug only within the examples and will be fixed with the next release.

**Comment by testower** [comment]
The reason I opened the bug is that I can't get react-intersection-observer to work in IE11 *or* Edge, even with the polyfill loaded.

Am I correct in understanding that it should work in Edge despite the open issue there, because the polyfill will handle it?

Then why it doesn't work in IE11 I'm not sure. It seems like the onChange handler isn't called. I will try and find a reproducible case.

**Comment by Rendez** [comment]
I've released a new version which includes the necessary polyfills for storybook.

**Comment by Rendez** [comment]
@testower I am closing this bug since the issue with the polyfill is resolved on the examples page. If you're having issues with the snippet you provided, please create an example using [codesandbox](https://codesandbox.io/) using the v0.4.0 version.

**Comment by testower** [comment]
Cheers, This is the minimal example I have that fails in Edge:

https://codesandbox.io/s/3vv2nw8zvm

Possibly an issue with the HOC, but I can't figure out what exactly. As far as I can tell, the onChange provided isn't fired.

**Comment by Rendez** [comment]
I've reviewed your example. Empty DIV's are zero-height. Older implementations of Chrome, and Edge 14/15 I believe, exhibit this old behavior. The spec was changed a while back to match edge-adjacent intersections (which would match the 0 pixel DIV). You can fix your example with:

```jsx
return (
  <div style={{ minHeight: 1 }}>
    {content}
  </div>
);
```

Let me know if this fixes your issue.

PS: to get isIntersection you'll have to import the polyfill in the codesandbox example.

**Comment by testower** [comment]
Thanks! I had completely ignored the logic that involves the intersection ratio, but it makes total sense to only care about isIntersecting in my implementation.

So taking care of that and the minHeight fixes the Edge issue. But I still can't get IE11 to work. Will try and get something reproducable, but struggling to get even codesandbox to load there.

**Comment by testower** [comment]
Oh, I suppose this is due to:

```Support for _Map_, _Symbol_ and other native features and primitives is required. Consider using a polyfill for IE < 11 and older browsers. If you're using babel include `"babel-polyfill"` somewhere to your codebase.```

**Comment by Rendez** [comment]
You're right, it should say to support IE in general, and any other browser lacking support for basic ES2015 features.

I would expect most users to load the transpiled version found in lib. You can include the transpiled version from `lib/js/*` available both from the npm release (npm install-ing the package) and running `[yarn build:js](https://github.com/researchgate/react-intersection-observer/blob/master/package.json#L85)`, your choice.

**Comment by testower** [comment]
Thanks for that. I tried to do that actually, and it didn't really make a difference for IE11.

Just to be clear, is it your module that requires additional polyfilling or is it the intersection-observer?

Either way, do you know which polyfills are required exactly?

**Comment by Rendez** [comment]
> Just to be clear, is it your module that requires additional polyfilling or is it the intersection-observer polyfill?

I decided to make the source ES2015-compatible only, so I don't include polyfills for ES5 with it. That means that @researchgate/react-intersection-observer requires Map/Set/Symbol to be polyfilled.

> I'm really not sure what I'm doing wrong here. Including babel-polyfill fixes the issue in IE11

Indeed, you've fixed the issue. You can select only certain parts of babel-polyfill to leave KBs out. There is more than 1 way to only use the parts of babel-polyfill you need (Map/Set/Symbol in your case), and I described already some of them (babel-preset-env). I don't want to repeat myself but I already gave you the answer, the rest you need to seek out for yourself as it is totally outside the scope of this library.

**Comment by testower** [comment]
Please forgive me for making you repeat yourself. I see now I missed your edit on the comment I replied to. There were essentially two things I was asking (which module required polyfilling and exactly which polyfill was required). You have answered both. Thanks for your patience.
